### ISSUE TITLE
3차과제 마감일 관련

### ISSUE THREAD

**Issue by HuikyungJo** [seohyun0120/software_engineering#7]
3차과제 마감일이 12/21 금요일입니다!
과제도 많고 곧 기말시험기간이라 어떻게 하는 게 좋을지 의견 말해주세용 :)

1. 다음주 금요일(12/7)까지 전체코드 완성
2. 모든 기말 시험이 끝난 후 전체코드 완성

**Comment by HuikyungJo** [comment]
잘못 올렸습니다

**Comment by seohyun0120** [comment]
1번이 좋을 것 같습니다~~ 저는 20일까지 시험을 봐서요...

**Comment by lbhsos** [comment]
저도 1번이 좋을 것 같아요!
95퍼센트 정도는 이번 주말까지 완료하겠습니다 :)

**Comment by HuikyungJo** [comment]
그럼 모두 1번 의견에 동의한 것으로 issue close하겠습니당~!
